### ISSUE TITLE
A string containing a name of the page would be accepted.

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/FB-Spider#1]
The top 5 results related to the accepted `'string'` would be accepted and top 5 results would be shown.
The user would be able to select from the options shown.

**Comment by nemani** [comment]
Hey! I saw your project through KWoC. 
Can I be assigned to this? Also can you elaborate this issue a bit?

**Comment by Parth-Vader** [comment]
First try running the program on your pc.
Report any issues that you receive.

**Comment by rusrushal13** [comment]
Hey! I am having issues with Authorization, how to resolve that?

**Comment by Parth-Vader** [comment]
@rusrushal13 You have to make a Facebook developer account and register an app.
Then you would receive an access token.
See this : https://facepy.readthedocs.io/en/latest/usage/graph-api.html
                https://developers.facebook.com/docs/graph-api

**Comment by rusrushal13** [comment]
This issue is only about automating the process of findmyfbid, if I get it right?
And is there anywhere else I could talk to you(hangouts, FB, slack, gitter or elsewhere), I have much more doubts on this program.

**Comment by Parth-Vader** [comment]
@rusrushal13 Add me on Facebook. 
https://www.facebook.com/ParthVerma4
