### ISSUE TITLE
Improve the README.md

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/FB-Spider#13]
Write all the steps and give all the necessary instructions

**Comment by dhruvapte26** [comment]
@Parth-Vader , require more on this issue. 
Copyrights included?
[https://github.com/the-ethan-hunt/FB-Spider/blob/master/README.md](url)

**Comment by Parth-Vader** [comment]
Make the requirements point-wise.
No need for copyright as of now.
Add the instructions to contribute in MarkDown format.
