### ISSUE TITLE
HTML page to be modified.

### ISSUE THREAD

**Issue by Parth-Vader** [Parth-Vader/FB-Spider#3]
1)The page needs to be prettier
2)Different color schemes can be used
3)The links of the commenters and posts would be shown.

**Comment by ronalddas** [comment]
@Parth-Vader Hi, after running the program. The table.html files just contains one cell with "data" in it. and nothing else

**Comment by Parth-Vader** [comment]
@ronalddas Create another issue. Don't comment in this issue.

**Comment by aditodkar** [comment]
Hi can I work on this issue?

**Comment by Parth-Vader** [comment]
Sure.
