### ISSUE TITLE
adding setup.py instead of requirments.txt

### ISSUE THREAD

**Issue by dibyasonu** [Parth-Vader/FB-Spider#34]

**Comment by dibyasonu** [comment]
I would like to work on this issue if u want

**Comment by Parth-Vader** [comment]
@dibyasonu Sure. It should be installable via `pip` - by `pip install .`.

**Comment by vchrombie** [comment]
Hello, I am interested in contributing to this issue. 
Can I work on this?

**Comment by Parth-Vader** [comment]
@vchrombie Hi, I think @dibyasonu is working on this.You can try other issues.

**Comment by vchrombie** [comment]
That's fine!
If you have anything to do, I will help you.

Thank You.
