### ISSUE TITLE
Page not found error

### ISSUE THREAD

**Issue by dibyasonu** [Parth-Vader/FB-Spider#36]
When no page is found for a given input there is an error while traversing the search_res['data'] list as nothing is present and program stops abruptly showing error message

**Comment by dibyasonu** [comment]
Can i work on this issue.. I have already made required changes in my repo.
[link](https://github.com/dibyasonu/FB-Spider/commit/1ff2fa6c6bf84ff427979275cf5822fb505eb4cc)
If u want i can send the PR

**Comment by Parth-Vader** [comment]
Sure.
