### ISSUE TITLE
i think we should have an option in starting of app where it should ask whether to display the latest comments or comments with most likes..

### ISSUE THREAD

**Issue by prakhar1234** [Parth-Vader/FB-Spider#39]
In this i am trying to say that if users type ''1'' then it should show the 5 comments with most like and else it should be 5 latest ones

**Comment by Parth-Vader** [comment]
@prakhar1234 Agree with you. Also, there could be an option to replace 5 (which is hardcoded) to any number that the user desires.

**Comment by prakhar1234** [comment]
cool will work on this ..
