### ISSUE TITLE
No variable named YOUR_ACCESS_TOKEN

### ISSUE THREAD

**Issue by rahuldcoder** [Parth-Vader/FB-Spider#56]
There is no variable named  YOUR_ACCESS_TOKEN in graph.py.

**Comment by Parth-Vader** [comment]
@rahuldcoder Yes, there were some changes made to the program just today, the README.md is yet to be updated - see #55 .
You need to install via `pip install --editable .` and then run `fbspider initialise`, and then run `fbspider search`.

**Comment by Parth-Vader** [comment]
@rahuldcoder Look at the new instructions.

**Comment by rahuldcoder** [comment]
Great
